language: python
python:
  - "pypy"
  - "pypy3"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install:
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py develop
script:
  py.test -v --cov tinydb
after_success:
  coveralls
